"""Shared ticker → company name mapping for the ConvFinQA sample scripts.

Both ``render_convfinqa_pdfs.py`` (H1 labels in the rendered PDF) and
``convert_convfinqa.py`` (natural-language user queries in ``--agent-retrieval``
mode) need the same canonical mapping. Keep it here so the two scripts cannot
drift.

Covers the 133 tickers present in the ConvFinQA train+dev splits.
"""

from __future__ import annotations


TICKER_TO_COMPANY: dict[str, str] = {
    "AAL": "American Airlines Group",
    "AAP": "Advance Auto Parts",
    "AAPL": "Apple",
    "ABMD": "Abiomed",
    "ADBE": "Adobe",
    "ADI": "Analog Devices",
    "AES": "AES Corporation",
    "ALLE": "Allegion",
    "ALXN": "Alexion Pharmaceuticals",
    "AMAT": "Applied Materials",
    "AMT": "American Tower",
    "ANET": "Arista Networks",
    "ANSS": "Ansys",
    "AON": "Aon",
    "AOS": "A. O. Smith",
    "APD": "Air Products and Chemicals",
    "APTV": "Aptiv",
    "AWK": "American Water Works",
    "BDX": "Becton Dickinson",
    "BKNG": "Booking Holdings",
    "BKR": "Baker Hughes",
    "BLK": "BlackRock",
    "BLL": "Ball Corporation",
    "C": "Citigroup",
    "CAG": "Conagra Brands",
    "CAT": "Caterpillar",
    "CB": "Chubb",
    "CDNS": "Cadence Design Systems",
    "CDW": "CDW Corporation",
    "CE": "Celanese",
    "CMCSA": "Comcast",
    "CME": "CME Group",
    "CNC": "Centene",
    "D": "Dominion Energy",
    "DG": "Dollar General",
    "DISCA": "Discovery Communications",
    "DISH": "DISH Network",
    "DRE": "Duke Realty",
    "DVN": "Devon Energy",
    "ECL": "Ecolab",
    "EL": "Estée Lauder Companies",
    "EMN": "Eastman Chemical",
    "EMR": "Emerson Electric",
    "EOG": "EOG Resources",
    "ETFC": "E*TRADE Financial",
    "ETR": "Entergy",
    "EW": "Edwards Lifesciences",
    "EXPD": "Expeditors International",
    "EXR": "Extra Space Storage",
    "FBHS": "Fortune Brands Home & Security",
    "FIS": "Fidelity National Information Services",
    "FITB": "Fifth Third Bancorp",
    "FRT": "Federal Realty Investment Trust",
    "FTV": "Fortive",
    "GIS": "General Mills",
    "GPN": "Global Payments",
    "GRMN": "Garmin",
    "GS": "Goldman Sachs",
    "HFC": "HollyFrontier",
    "HIG": "Hartford Financial Services",
    "HII": "Huntington Ingalls Industries",
    "HOLX": "Hologic",
    "HST": "Host Hotels & Resorts",
    "HUM": "Humana",
    "HWM": "Howmet Aerospace",
    "ILMN": "Illumina",
    "INTC": "Intel",
    "IP": "International Paper",
    "IPG": "Interpublic Group",
    "IQV": "IQVIA",
    "JKHY": "Jack Henry & Associates",
    "JPM": "JPMorgan Chase",
    "K": "Kellogg",
    "KHC": "Kraft Heinz",
    "KIM": "Kimco Realty",
    "KMI": "Kinder Morgan",
    "L": "Loews",
    "LKQ": "LKQ Corporation",
    "LLY": "Eli Lilly",
    "LMT": "Lockheed Martin",
    "MA": "Mastercard",
    "MAA": "Mid-America Apartment Communities",
    "MAR": "Marriott International",
    "MAS": "Masco",
    "MKTX": "MarketAxess",
    "MMM": "3M",
    "MO": "Altria Group",
    "MRK": "Merck",
    "MRO": "Marathon Oil",
    "MS": "Morgan Stanley",
    "MSI": "Motorola Solutions",
    "NCLH": "Norwegian Cruise Line Holdings",
    "NKE": "Nike",
    "NTAP": "NetApp",
    "NWS": "News Corporation",
    "OKE": "ONEOK",
    "ORLY": "O'Reilly Automotive",
    "PKG": "Packaging Corporation of America",
    "PM": "Philip Morris International",
    "PNC": "PNC Financial Services",
    "PPG": "PPG Industries",
    "RCL": "Royal Caribbean Cruises",
    "RE": "Everest Re Group",
    "REGN": "Regeneron Pharmaceuticals",
    "RL": "Ralph Lauren",
    "RSG": "Republic Services",
    "SLB": "Schlumberger",
    "SLG": "SL Green Realty",
    "SNA": "Snap-on",
    "SNPS": "Synopsys",
    "SPGI": "S&P Global",
    "STT": "State Street",
    "STZ": "Constellation Brands",
    "SWKS": "Skyworks Solutions",
    "SYY": "Sysco",
    "TFX": "Teleflex",
    "TMUS": "T-Mobile US",
    "TROW": "T. Rowe Price",
    "TSCO": "Tractor Supply Company",
    "TXN": "Texas Instruments",
    "UA": "Under Armour (Class C)",
    "UAA": "Under Armour (Class A)",
    "UNP": "Union Pacific",
    "UPS": "United Parcel Service",
    "V": "Visa",
    "VLO": "Valero Energy",
    "VNO": "Vornado Realty Trust",
    "VRTX": "Vertex Pharmaceuticals",
    "VTR": "Ventas",
    "WELL": "Welltower",
    "WMT": "Walmart",
    "WRK": "WestRock",
    "ZBH": "Zimmer Biomet",
}


def company_label(ticker: str) -> str:
    """Render a company label as ``Company Name (TICKER)`` if mapped,
    otherwise just ``TICKER``."""
    name = TICKER_TO_COMPANY.get(ticker)
    return f"{name} ({ticker})" if name else ticker
